import { getAllPokemons } from "@/services/ApiService";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Pokemon Page",
  description: "Pokemon Page Generated By Poke API",
};
export default async function Home() {
  const pokemons = await getAllPokemons();
  return <div className=""></div>;
}
