import PokemonsData from "@/components/home/Pokemons";
import { getAllPokemons } from "@/services/ApiService";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pokemon Page",
  description: "Pokemon Page Generated By Poke API",
};
//Converting static page to dynamic
export const dynamic = "force-dynamic";

export default async function Home() {
  //Fetching Pokemons in SSR
  const pokemons = await getAllPokemons();
  if (!pokemons)
    return <span className="text-red-500">Failed to Load Data</span>;
  return <PokemonsData data={pokemons.data.results} />;
}
